include = ["**/*.toml", "**/*.toml.tmpl"]

[[rule]]
keys = ["*"]

[rule.formatting]
array_auto_collapse = false

[[rule]]
keys = ["*.*"]

[rule.formatting]
array_auto_collapse = true

[[rule]]
include = ["**/.chezmoidata/*tools.toml"]
keys = ["*.*"]

[rule.formatting]
array_auto_collapse = false
array_trailing_comma = false
indent_string = "    "
