# Rotate by 90 degrees clockwise
#Alt+RIGHT no-osd vf add rotate=1
# Rotate by 90 degrees counterclockwise
#Alt+LEFT no-osd vf add rotate=2

Alt+RIGHT no-osd cycle video-rotate 90
Alt+LEFT no-osd cycle video-rotate -90

# Pan when zoomed
Alt+n add video-pan-x 0.05
Alt+h add video-pan-x -0.05
Alt+l add video-pan-y 0.05
Alt+k add video-pan-y -0.05
Alt+BS set video-zoom 0; set video-pan-x 0; set video-pan-y 0

# Show playlist
CTRL+l script-message osc-playlist

# Playlist skipping
PGDWN playlist-next
PGUP playlist-prev


Alt+9 script-message Quick_Scale "5120" "1440" "1.0" "-1"

# Video cropping
# Alt+c start-crop
# SHIFT+Alt+c

# File deletion
# mp.add_key_binding("ctrl+DEL", "delete_file", mark_delete)
# mp.add_key_binding("alt+DEL", "list_marks", list_marks)
# mp.add_key_binding("ctrl+shift+DEL", "clear_list", function() mp.osd_message("Undelete all"); del_list = {}; end)
# Ctrl+d delete_file
# Alt+d list_marks
# Ctrl+Shift+d clear_list

