#profile=default
hwdec=auto
hwdec-codecs=all
loop=inf
ytdl-raw-options=yes-playlist=
interpolation

[default]
# nothing here


[low-rez]
profile-desc=cond:p.width<=1920 and p.height<=1080
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
tscale=oversample
profile=gpu-hq


[hq]
# No special settings for hq, to use defaults
profile-desc=cond:p.width>1920 and p.height>1080


