profile=default
ontop=yes
loop=inf
ytdl-raw-options=yes-playlist=
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
tscale=oversample

# Extra mpv options
# input-ipc-server=/tmp/mpvpipe --loop=inf

[default]
interpolation

