#profile=default
hwdec=auto
hwdec-codecs=all
loop=inf
ytdl-raw-options=yes-playlist=
#vo=xv
video-sync=display-resample
interpolation
autofit-larger=100%x100%


[default]
# nothing here


[low-rez]
profile-desc=cond:get('width',0) <= 1920 and get('height',0) <= 1080
profile=gpu-hq
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
tscale=oversample
glsl-shaders="~~/shaders/FSRCNNX_x2_16-0-4-1.glsl"
#glsl-shaders-append="~~/shaders/ravu-zoom-r4.hook"


[hq]
# No special settings for hq, to use defaults
profile-desc=cond:get('width',0) > 1920 and get('height',0) > 1080
#vo=gpu


